### ISSUE TITLE
XSim v2 installation

### ISSUE THREAD

**Issue by datasciencetoolkit** [reworkhow/XSim.jl#24]
Hi Guys,

I get the following error when installing XSim v2.0.3 on Julia 1.3.1 and 1.4.1. Do you have any clue about what might be the possible reason?

Info: Precompiling XSim [3d41126b-a46a-5bdb-b7a1-7ea6cc35a8ef]
└ @ Base loading.jl:1273
ERROR: LoadError: UndefVarError: schematype not defined
Stacktrace:
 [1] include at ./boot.jl:328 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1105
 [3] include(::Module, ::String) at ./Base.jl:31
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:330 [inlined]
 [6] eval(::Expr) at ./client.jl:425
 [7] top-level scope at ./none:3
in expression starting at /usr/home/qgg/emre/.julia/packages/XSim/MCjcH/src/XSim.jl:3
Failed to precompile XSim [3d41126b-a46a-5bdb-b7a1-7ea6cc35a8ef] to /usr/home/qgg/emre/.julia/compiled/v1.3/XSim/fVVb1_AUEbL.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283
 [3] _require(::Base.PkgId) at ./loading.jl:1024
 [4] require(::Base.PkgId) at ./loading.jl:922
 [5] require(::Module, ::Symbol) at ./loading.jl:917
 [6] top-level scope at In[4]:1

**Comment by Poissonfish** [comment]
Hi Emre,

Would you try replacing `using CSV: schematype` with `using CSV` in the file src/XSim.jl:3? If it fixes your issue, I'll push this update to the latest release. Thank you.

James

**Comment by datasciencetoolkit** [comment]
Thanks James, it fixed the problem.

**Comment by datasciencetoolkit** [comment]
Hi James,

I reopened this, because I think there is an issue with outputting functions.
Briefly, output.jl is not a part of the package as i can see.

I tried to manually fix the issue, but I could not also find the first 3 lines (functions) in the output.jl anywhere. Commenting them out caused other issues ("not found" functions for ex. getOurPhenVals() ). I could not really dig in so much, but seems like a general issue.

**Comment by datasciencetoolkit** [comment]
Here is my solution.

I commented out these in the output/output.jl

- genotype.jl
- phenotype.jl
- moreInfo.jl

I added the following to the XSim.jl 

- include("output/output.jl")
- export outputPedigree, outputHapData, outputGenData, outputCatData, outputMarkerWithQTLEffects

I modified outputPedigree() in output.jl:

function outputPedigree(my::Cohort, fileName::AbstractString)
    pedText  = fileName * ".ped"
    genText  = fileName * ".gen"
    brcText  = fileName * ".brc"
    pheText  = fileName * ".phe"
    pedStream = open(pedText,"a")
    genStream = open(genText,"a")
    brcStream = open(brcText,"a")
    pheStream = open(pheText,"a")
#############old function "getOurPhenVals()" is in the current XSim. I am not using anyways.
#######    get_phenotypes(my,"XSim")
    nTraits = gb.n_traits  ####### no GLOBAL.LRes in XSim, so I just replaced with this.
    for (k,animal) = enumerate(my.animals)
        if k%1000 == 0
            println("outputPedigree(): ", k)
        end
        genotypes=get_genotypes(animal)
############## In the current XSim, it reads animal.myID etc.. I corrected those everywhere in this function as well
        @printf(pedStream,  "%19d %19d %19d \n", animal.ID, animal.sire.ID, animal.dam.ID)
        @printf(brcStream,  "%19d ", animal.ID)
############## breedComp not available
#######        for j=1:length(animal.breedComp)
#######            @printf(brcStream, "%5.3f ", animal.breedComp[j])
#######        end
        @printf(brcStream, "\n")
        @printf(pheStream, "%19d ", animal.ID)
############ animal.val.p not available!!!
#######       for i=1:nTraits
#######           @printf(pheStream, "%11.3f ",animal.val_p[i])
#######        end
        for i=1:nTraits
            @printf(pheStream, "%11.3f ",animal.val_g[i])
        end
        @printf(pheStream, "\n")
        @printf(genStream, "%19d", animal.ID)
        for j=1:length(genotypes)
            @printf(genStream, "%2d", genotypes[j])
        end
        @printf(genStream, "\n")
    end
    close(pheStream)
    close(brcStream)
    close(pedStream)
    close(genStream)
end

Actually, I would rather a phenotype file (*.phe) with, phenotype, BV, and residual for all traits.

This works for me, as i am not applying any selection, and I can simulate phenotypes after all genotypic data is being simulated. But I think it wont work in other cases.

**Comment by Poissonfish** [comment]
Hi Emre,

Thanks for the reminder and the effort! You're right, at this point, `output.jl` is never used by XSimV2. I've removed it from the repository and it shouldn't bother users in selection tasks now.
